In [2]:
import numpy as np

In [3]:
A = np.array([1,2,3])

In [4]:
A

array([1, 2, 3])

In [5]:
B = np.array([1,2,3])

In [6]:
B

array([1, 2, 3])

In [7]:
A+B

array([2, 4, 6])

In [9]:
%%timeit
A+B

982 ns ± 131 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
a = [1,2,3]
b = [1,2,3]

In [11]:
%%timeit
a+b

163 ns ± 10.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
